/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as PresidenteSlugRouteImport } from './routes/presidente.$slug'
import { Route as LiganteSlugRouteImport } from './routes/ligante.$slug'
import { Route as DiretorSlugRouteImport } from './routes/diretor.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresidenteSlugRoute = PresidenteSlugRouteImport.update({
  id: '/presidente/$slug',
  path: '/presidente/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiganteSlugRoute = LiganteSlugRouteImport.update({
  id: '/ligante/$slug',
  path: '/ligante/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretorSlugRoute = DiretorSlugRouteImport.update({
  id: '/diretor/$slug',
  path: '/diretor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DiretorSlugRoute: typeof DiretorSlugRoute
  LiganteSlugRoute: typeof LiganteSlugRoute
  PresidenteSlugRoute: typeof PresidenteSlugRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presidente/$slug': {
      id: '/presidente/$slug'
      path: '/presidente/$slug'
      fullPath: '/presidente/$slug'
      preLoaderRoute: typeof PresidenteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligante/$slug': {
      id: '/ligante/$slug'
      path: '/ligante/$slug'
      fullPath: '/ligante/$slug'
      preLoaderRoute: typeof LiganteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretor/$slug': {
      id: '/diretor/$slug'
      path: '/diretor/$slug'
      fullPath: '/diretor/$slug'
      preLoaderRoute: typeof DiretorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DiretorSlugRoute: DiretorSlugRoute,
  LiganteSlugRoute: LiganteSlugRoute,
  PresidenteSlugRoute: PresidenteSlugRoute,
  SlugIndexRoute: SlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
