/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LigasRouteImport } from './routes/ligas'
import { Route as CamedPainelRouteImport } from './routes/camed-painel'
import { Route as CamedGaleriaRouteImport } from './routes/camed-galeria'
import { Route as CamedRouteImport } from './routes/camed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtleticaRouteImport } from './routes/atletica'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AaamdRouteImport } from './routes/aaamd'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as PresidenteSlugRouteImport } from './routes/presidente.$slug'
import { Route as LiganteSlugRouteImport } from './routes/ligante.$slug'
import { Route as DiretorSlugRouteImport } from './routes/diretor.$slug'
import { Route as CoordenacaoFeriadosRouteImport } from './routes/coordenacao.feriados'
import { Route as CoordenacaoCurriculoRouteImport } from './routes/coordenacao.curriculo'
import { Route as CoordenacaoCronogramaRouteImport } from './routes/coordenacao.cronograma'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsMpWebhookRouteImport } from './routes/api/public/payments/mp-webhook'
import { Route as ApiPublicPaymentsMpOauthStartRouteImport } from './routes/api/public/payments/mp-oauth-start'
import { Route as ApiPublicPaymentsMpOauthCallbackRouteImport } from './routes/api/public/payments/mp-oauth-callback'
import { Route as ApiPublicHooksStorageCleanupRouteImport } from './routes/api/public/hooks/storage-cleanup'
import { Route as ApiPublicCronMarkOverdueRouteImport } from './routes/api/public/cron/mark-overdue'
import { Route as ApiPublicCronEventSnapshotRouteImport } from './routes/api/public/cron/event-snapshot'
import { Route as ApiPublicCronEventRemindersRouteImport } from './routes/api/public/cron/event-reminders'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasRoute = LigasRouteImport.update({
  id: '/ligas',
  path: '/ligas',
  getParentRoute: () => rootRouteImport,
} as any)
const CamedPainelRoute = CamedPainelRouteImport.update({
  id: '/camed-painel',
  path: '/camed-painel',
  getParentRoute: () => rootRouteImport,
} as any)
const CamedGaleriaRoute = CamedGaleriaRouteImport.update({
  id: '/camed-galeria',
  path: '/camed-galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const CamedRoute = CamedRouteImport.update({
  id: '/camed',
  path: '/camed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtleticaRoute = AtleticaRouteImport.update({
  id: '/atletica',
  path: '/atletica',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AaamdRoute = AaamdRouteImport.update({
  id: '/aaamd',
  path: '/aaamd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresidenteSlugRoute = PresidenteSlugRouteImport.update({
  id: '/presidente/$slug',
  path: '/presidente/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiganteSlugRoute = LiganteSlugRouteImport.update({
  id: '/ligante/$slug',
  path: '/ligante/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretorSlugRoute = DiretorSlugRouteImport.update({
  id: '/diretor/$slug',
  path: '/diretor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenacaoFeriadosRoute = CoordenacaoFeriadosRouteImport.update({
  id: '/coordenacao/feriados',
  path: '/coordenacao/feriados',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenacaoCurriculoRoute = CoordenacaoCurriculoRouteImport.update({
  id: '/coordenacao/curriculo',
  path: '/coordenacao/curriculo',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordenacaoCronogramaRoute = CoordenacaoCronogramaRouteImport.update({
  id: '/coordenacao/cronograma',
  path: '/coordenacao/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMpWebhookRoute =
  ApiPublicPaymentsMpWebhookRouteImport.update({
    id: '/api/public/payments/mp-webhook',
    path: '/api/public/payments/mp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMpOauthStartRoute =
  ApiPublicPaymentsMpOauthStartRouteImport.update({
    id: '/api/public/payments/mp-oauth-start',
    path: '/api/public/payments/mp-oauth-start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMpOauthCallbackRoute =
  ApiPublicPaymentsMpOauthCallbackRouteImport.update({
    id: '/api/public/payments/mp-oauth-callback',
    path: '/api/public/payments/mp-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStorageCleanupRoute =
  ApiPublicHooksStorageCleanupRouteImport.update({
    id: '/api/public/hooks/storage-cleanup',
    path: '/api/public/hooks/storage-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMarkOverdueRoute =
  ApiPublicCronMarkOverdueRouteImport.update({
    id: '/api/public/cron/mark-overdue',
    path: '/api/public/cron/mark-overdue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronEventSnapshotRoute =
  ApiPublicCronEventSnapshotRouteImport.update({
    id: '/api/public/cron/event-snapshot',
    path: '/api/public/cron/event-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronEventRemindersRoute =
  ApiPublicCronEventRemindersRouteImport.update({
    id: '/api/public/cron/event-reminders',
    path: '/api/public/cron/event-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aaamd': typeof AaamdRoute
  '/admin': typeof AdminRoute
  '/aluno': typeof AlunoRoute
  '/atletica': typeof AtleticaRoute
  '/auth': typeof AuthRoute
  '/camed': typeof CamedRoute
  '/camed-galeria': typeof CamedGaleriaRoute
  '/camed-painel': typeof CamedPainelRoute
  '/ligas': typeof LigasRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/coordenacao/cronograma': typeof CoordenacaoCronogramaRoute
  '/coordenacao/curriculo': typeof CoordenacaoCurriculoRoute
  '/coordenacao/feriados': typeof CoordenacaoFeriadosRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/api/public/cron/event-reminders': typeof ApiPublicCronEventRemindersRoute
  '/api/public/cron/event-snapshot': typeof ApiPublicCronEventSnapshotRoute
  '/api/public/cron/mark-overdue': typeof ApiPublicCronMarkOverdueRoute
  '/api/public/hooks/storage-cleanup': typeof ApiPublicHooksStorageCleanupRoute
  '/api/public/payments/mp-oauth-callback': typeof ApiPublicPaymentsMpOauthCallbackRoute
  '/api/public/payments/mp-oauth-start': typeof ApiPublicPaymentsMpOauthStartRoute
  '/api/public/payments/mp-webhook': typeof ApiPublicPaymentsMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aaamd': typeof AaamdRoute
  '/admin': typeof AdminRoute
  '/aluno': typeof AlunoRoute
  '/atletica': typeof AtleticaRoute
  '/auth': typeof AuthRoute
  '/camed': typeof CamedRoute
  '/camed-galeria': typeof CamedGaleriaRoute
  '/camed-painel': typeof CamedPainelRoute
  '/ligas': typeof LigasRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/coordenacao/cronograma': typeof CoordenacaoCronogramaRoute
  '/coordenacao/curriculo': typeof CoordenacaoCurriculoRoute
  '/coordenacao/feriados': typeof CoordenacaoFeriadosRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug': typeof SlugIndexRoute
  '/api/public/cron/event-reminders': typeof ApiPublicCronEventRemindersRoute
  '/api/public/cron/event-snapshot': typeof ApiPublicCronEventSnapshotRoute
  '/api/public/cron/mark-overdue': typeof ApiPublicCronMarkOverdueRoute
  '/api/public/hooks/storage-cleanup': typeof ApiPublicHooksStorageCleanupRoute
  '/api/public/payments/mp-oauth-callback': typeof ApiPublicPaymentsMpOauthCallbackRoute
  '/api/public/payments/mp-oauth-start': typeof ApiPublicPaymentsMpOauthStartRoute
  '/api/public/payments/mp-webhook': typeof ApiPublicPaymentsMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aaamd': typeof AaamdRoute
  '/admin': typeof AdminRoute
  '/aluno': typeof AlunoRoute
  '/atletica': typeof AtleticaRoute
  '/auth': typeof AuthRoute
  '/camed': typeof CamedRoute
  '/camed-galeria': typeof CamedGaleriaRoute
  '/camed-painel': typeof CamedPainelRoute
  '/ligas': typeof LigasRoute
  '/painel': typeof PainelRoute
  '/perfil': typeof PerfilRoute
  '/coordenacao/cronograma': typeof CoordenacaoCronogramaRoute
  '/coordenacao/curriculo': typeof CoordenacaoCurriculoRoute
  '/coordenacao/feriados': typeof CoordenacaoFeriadosRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/api/public/cron/event-reminders': typeof ApiPublicCronEventRemindersRoute
  '/api/public/cron/event-snapshot': typeof ApiPublicCronEventSnapshotRoute
  '/api/public/cron/mark-overdue': typeof ApiPublicCronMarkOverdueRoute
  '/api/public/hooks/storage-cleanup': typeof ApiPublicHooksStorageCleanupRoute
  '/api/public/payments/mp-oauth-callback': typeof ApiPublicPaymentsMpOauthCallbackRoute
  '/api/public/payments/mp-oauth-start': typeof ApiPublicPaymentsMpOauthStartRoute
  '/api/public/payments/mp-webhook': typeof ApiPublicPaymentsMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aaamd'
    | '/admin'
    | '/aluno'
    | '/atletica'
    | '/auth'
    | '/camed'
    | '/camed-galeria'
    | '/camed-painel'
    | '/ligas'
    | '/painel'
    | '/perfil'
    | '/coordenacao/cronograma'
    | '/coordenacao/curriculo'
    | '/coordenacao/feriados'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug/'
    | '/api/public/cron/event-reminders'
    | '/api/public/cron/event-snapshot'
    | '/api/public/cron/mark-overdue'
    | '/api/public/hooks/storage-cleanup'
    | '/api/public/payments/mp-oauth-callback'
    | '/api/public/payments/mp-oauth-start'
    | '/api/public/payments/mp-webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aaamd'
    | '/admin'
    | '/aluno'
    | '/atletica'
    | '/auth'
    | '/camed'
    | '/camed-galeria'
    | '/camed-painel'
    | '/ligas'
    | '/painel'
    | '/perfil'
    | '/coordenacao/cronograma'
    | '/coordenacao/curriculo'
    | '/coordenacao/feriados'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug'
    | '/api/public/cron/event-reminders'
    | '/api/public/cron/event-snapshot'
    | '/api/public/cron/mark-overdue'
    | '/api/public/hooks/storage-cleanup'
    | '/api/public/payments/mp-oauth-callback'
    | '/api/public/payments/mp-oauth-start'
    | '/api/public/payments/mp-webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/aaamd'
    | '/admin'
    | '/aluno'
    | '/atletica'
    | '/auth'
    | '/camed'
    | '/camed-galeria'
    | '/camed-painel'
    | '/ligas'
    | '/painel'
    | '/perfil'
    | '/coordenacao/cronograma'
    | '/coordenacao/curriculo'
    | '/coordenacao/feriados'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug/'
    | '/api/public/cron/event-reminders'
    | '/api/public/cron/event-snapshot'
    | '/api/public/cron/mark-overdue'
    | '/api/public/hooks/storage-cleanup'
    | '/api/public/payments/mp-oauth-callback'
    | '/api/public/payments/mp-oauth-start'
    | '/api/public/payments/mp-webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AaamdRoute: typeof AaamdRoute
  AdminRoute: typeof AdminRoute
  AlunoRoute: typeof AlunoRoute
  AtleticaRoute: typeof AtleticaRoute
  AuthRoute: typeof AuthRoute
  CamedRoute: typeof CamedRoute
  CamedGaleriaRoute: typeof CamedGaleriaRoute
  CamedPainelRoute: typeof CamedPainelRoute
  LigasRoute: typeof LigasRoute
  PainelRoute: typeof PainelRoute
  PerfilRoute: typeof PerfilRoute
  CoordenacaoCronogramaRoute: typeof CoordenacaoCronogramaRoute
  CoordenacaoCurriculoRoute: typeof CoordenacaoCurriculoRoute
  CoordenacaoFeriadosRoute: typeof CoordenacaoFeriadosRoute
  DiretorSlugRoute: typeof DiretorSlugRoute
  LiganteSlugRoute: typeof LiganteSlugRoute
  PresidenteSlugRoute: typeof PresidenteSlugRoute
  SlugIndexRoute: typeof SlugIndexRoute
  ApiPublicCronEventRemindersRoute: typeof ApiPublicCronEventRemindersRoute
  ApiPublicCronEventSnapshotRoute: typeof ApiPublicCronEventSnapshotRoute
  ApiPublicCronMarkOverdueRoute: typeof ApiPublicCronMarkOverdueRoute
  ApiPublicHooksStorageCleanupRoute: typeof ApiPublicHooksStorageCleanupRoute
  ApiPublicPaymentsMpOauthCallbackRoute: typeof ApiPublicPaymentsMpOauthCallbackRoute
  ApiPublicPaymentsMpOauthStartRoute: typeof ApiPublicPaymentsMpOauthStartRoute
  ApiPublicPaymentsMpWebhookRoute: typeof ApiPublicPaymentsMpWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas': {
      id: '/ligas'
      path: '/ligas'
      fullPath: '/ligas'
      preLoaderRoute: typeof LigasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camed-painel': {
      id: '/camed-painel'
      path: '/camed-painel'
      fullPath: '/camed-painel'
      preLoaderRoute: typeof CamedPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camed-galeria': {
      id: '/camed-galeria'
      path: '/camed-galeria'
      fullPath: '/camed-galeria'
      preLoaderRoute: typeof CamedGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camed': {
      id: '/camed'
      path: '/camed'
      fullPath: '/camed'
      preLoaderRoute: typeof CamedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletica': {
      id: '/atletica'
      path: '/atletica'
      fullPath: '/atletica'
      preLoaderRoute: typeof AtleticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aaamd': {
      id: '/aaamd'
      path: '/aaamd'
      fullPath: '/aaamd'
      preLoaderRoute: typeof AaamdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presidente/$slug': {
      id: '/presidente/$slug'
      path: '/presidente/$slug'
      fullPath: '/presidente/$slug'
      preLoaderRoute: typeof PresidenteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligante/$slug': {
      id: '/ligante/$slug'
      path: '/ligante/$slug'
      fullPath: '/ligante/$slug'
      preLoaderRoute: typeof LiganteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretor/$slug': {
      id: '/diretor/$slug'
      path: '/diretor/$slug'
      fullPath: '/diretor/$slug'
      preLoaderRoute: typeof DiretorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenacao/feriados': {
      id: '/coordenacao/feriados'
      path: '/coordenacao/feriados'
      fullPath: '/coordenacao/feriados'
      preLoaderRoute: typeof CoordenacaoFeriadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenacao/curriculo': {
      id: '/coordenacao/curriculo'
      path: '/coordenacao/curriculo'
      fullPath: '/coordenacao/curriculo'
      preLoaderRoute: typeof CoordenacaoCurriculoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordenacao/cronograma': {
      id: '/coordenacao/cronograma'
      path: '/coordenacao/cronograma'
      fullPath: '/coordenacao/cronograma'
      preLoaderRoute: typeof CoordenacaoCronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mp-webhook': {
      id: '/api/public/payments/mp-webhook'
      path: '/api/public/payments/mp-webhook'
      fullPath: '/api/public/payments/mp-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mp-oauth-start': {
      id: '/api/public/payments/mp-oauth-start'
      path: '/api/public/payments/mp-oauth-start'
      fullPath: '/api/public/payments/mp-oauth-start'
      preLoaderRoute: typeof ApiPublicPaymentsMpOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mp-oauth-callback': {
      id: '/api/public/payments/mp-oauth-callback'
      path: '/api/public/payments/mp-oauth-callback'
      fullPath: '/api/public/payments/mp-oauth-callback'
      preLoaderRoute: typeof ApiPublicPaymentsMpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/storage-cleanup': {
      id: '/api/public/hooks/storage-cleanup'
      path: '/api/public/hooks/storage-cleanup'
      fullPath: '/api/public/hooks/storage-cleanup'
      preLoaderRoute: typeof ApiPublicHooksStorageCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/mark-overdue': {
      id: '/api/public/cron/mark-overdue'
      path: '/api/public/cron/mark-overdue'
      fullPath: '/api/public/cron/mark-overdue'
      preLoaderRoute: typeof ApiPublicCronMarkOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/event-snapshot': {
      id: '/api/public/cron/event-snapshot'
      path: '/api/public/cron/event-snapshot'
      fullPath: '/api/public/cron/event-snapshot'
      preLoaderRoute: typeof ApiPublicCronEventSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/event-reminders': {
      id: '/api/public/cron/event-reminders'
      path: '/api/public/cron/event-reminders'
      fullPath: '/api/public/cron/event-reminders'
      preLoaderRoute: typeof ApiPublicCronEventRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AaamdRoute: AaamdRoute,
  AdminRoute: AdminRoute,
  AlunoRoute: AlunoRoute,
  AtleticaRoute: AtleticaRoute,
  AuthRoute: AuthRoute,
  CamedRoute: CamedRoute,
  CamedGaleriaRoute: CamedGaleriaRoute,
  CamedPainelRoute: CamedPainelRoute,
  LigasRoute: LigasRoute,
  PainelRoute: PainelRoute,
  PerfilRoute: PerfilRoute,
  CoordenacaoCronogramaRoute: CoordenacaoCronogramaRoute,
  CoordenacaoCurriculoRoute: CoordenacaoCurriculoRoute,
  CoordenacaoFeriadosRoute: CoordenacaoFeriadosRoute,
  DiretorSlugRoute: DiretorSlugRoute,
  LiganteSlugRoute: LiganteSlugRoute,
  PresidenteSlugRoute: PresidenteSlugRoute,
  SlugIndexRoute: SlugIndexRoute,
  ApiPublicCronEventRemindersRoute: ApiPublicCronEventRemindersRoute,
  ApiPublicCronEventSnapshotRoute: ApiPublicCronEventSnapshotRoute,
  ApiPublicCronMarkOverdueRoute: ApiPublicCronMarkOverdueRoute,
  ApiPublicHooksStorageCleanupRoute: ApiPublicHooksStorageCleanupRoute,
  ApiPublicPaymentsMpOauthCallbackRoute: ApiPublicPaymentsMpOauthCallbackRoute,
  ApiPublicPaymentsMpOauthStartRoute: ApiPublicPaymentsMpOauthStartRoute,
  ApiPublicPaymentsMpWebhookRoute: ApiPublicPaymentsMpWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
