/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CamedRouteImport } from './routes/camed'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as PresidenteSlugRouteImport } from './routes/presidente.$slug'
import { Route as LiganteSlugRouteImport } from './routes/ligante.$slug'
import { Route as DiretorSlugRouteImport } from './routes/diretor.$slug'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsMpWebhookRouteImport } from './routes/api/public/payments/mp-webhook'
import { Route as ApiPublicPaymentsMpOauthCallbackRouteImport } from './routes/api/public/payments/mp-oauth-callback'
import { Route as ApiPublicCronMarkOverdueRouteImport } from './routes/api/public/cron/mark-overdue'

const CamedRoute = CamedRouteImport.update({
  id: '/camed',
  path: '/camed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresidenteSlugRoute = PresidenteSlugRouteImport.update({
  id: '/presidente/$slug',
  path: '/presidente/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiganteSlugRoute = LiganteSlugRouteImport.update({
  id: '/ligante/$slug',
  path: '/ligante/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretorSlugRoute = DiretorSlugRouteImport.update({
  id: '/diretor/$slug',
  path: '/diretor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMpWebhookRoute =
  ApiPublicPaymentsMpWebhookRouteImport.update({
    id: '/api/public/payments/mp-webhook',
    path: '/api/public/payments/mp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsMpOauthCallbackRoute =
  ApiPublicPaymentsMpOauthCallbackRouteImport.update({
    id: '/api/public/payments/mp-oauth-callback',
    path: '/api/public/payments/mp-oauth-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMarkOverdueRoute =
  ApiPublicCronMarkOverdueRouteImport.update({
    id: '/api/public/cron/mark-overdue',
    path: '/api/public/cron/mark-overdue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/camed': typeof CamedRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/api/public/cron/mark-overdue': typeof ApiPublicCronMarkOverdueRoute
  '/api/public/payments/mp-oauth-callback': typeof ApiPublicPaymentsMpOauthCallbackRoute
  '/api/public/payments/mp-webhook': typeof ApiPublicPaymentsMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/camed': typeof CamedRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug': typeof SlugIndexRoute
  '/api/public/cron/mark-overdue': typeof ApiPublicCronMarkOverdueRoute
  '/api/public/payments/mp-oauth-callback': typeof ApiPublicPaymentsMpOauthCallbackRoute
  '/api/public/payments/mp-webhook': typeof ApiPublicPaymentsMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/camed': typeof CamedRoute
  '/diretor/$slug': typeof DiretorSlugRoute
  '/ligante/$slug': typeof LiganteSlugRoute
  '/presidente/$slug': typeof PresidenteSlugRoute
  '/$slug/': typeof SlugIndexRoute
  '/api/public/cron/mark-overdue': typeof ApiPublicCronMarkOverdueRoute
  '/api/public/payments/mp-oauth-callback': typeof ApiPublicPaymentsMpOauthCallbackRoute
  '/api/public/payments/mp-webhook': typeof ApiPublicPaymentsMpWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/camed'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug/'
    | '/api/public/cron/mark-overdue'
    | '/api/public/payments/mp-oauth-callback'
    | '/api/public/payments/mp-webhook'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/camed'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug'
    | '/api/public/cron/mark-overdue'
    | '/api/public/payments/mp-oauth-callback'
    | '/api/public/payments/mp-webhook'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/camed'
    | '/diretor/$slug'
    | '/ligante/$slug'
    | '/presidente/$slug'
    | '/$slug/'
    | '/api/public/cron/mark-overdue'
    | '/api/public/payments/mp-oauth-callback'
    | '/api/public/payments/mp-webhook'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CamedRoute: typeof CamedRoute
  DiretorSlugRoute: typeof DiretorSlugRoute
  LiganteSlugRoute: typeof LiganteSlugRoute
  PresidenteSlugRoute: typeof PresidenteSlugRoute
  SlugIndexRoute: typeof SlugIndexRoute
  ApiPublicCronMarkOverdueRoute: typeof ApiPublicCronMarkOverdueRoute
  ApiPublicPaymentsMpOauthCallbackRoute: typeof ApiPublicPaymentsMpOauthCallbackRoute
  ApiPublicPaymentsMpWebhookRoute: typeof ApiPublicPaymentsMpWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/camed': {
      id: '/camed'
      path: '/camed'
      fullPath: '/camed'
      preLoaderRoute: typeof CamedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presidente/$slug': {
      id: '/presidente/$slug'
      path: '/presidente/$slug'
      fullPath: '/presidente/$slug'
      preLoaderRoute: typeof PresidenteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligante/$slug': {
      id: '/ligante/$slug'
      path: '/ligante/$slug'
      fullPath: '/ligante/$slug'
      preLoaderRoute: typeof LiganteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretor/$slug': {
      id: '/diretor/$slug'
      path: '/diretor/$slug'
      fullPath: '/diretor/$slug'
      preLoaderRoute: typeof DiretorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mp-webhook': {
      id: '/api/public/payments/mp-webhook'
      path: '/api/public/payments/mp-webhook'
      fullPath: '/api/public/payments/mp-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/mp-oauth-callback': {
      id: '/api/public/payments/mp-oauth-callback'
      path: '/api/public/payments/mp-oauth-callback'
      fullPath: '/api/public/payments/mp-oauth-callback'
      preLoaderRoute: typeof ApiPublicPaymentsMpOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/mark-overdue': {
      id: '/api/public/cron/mark-overdue'
      path: '/api/public/cron/mark-overdue'
      fullPath: '/api/public/cron/mark-overdue'
      preLoaderRoute: typeof ApiPublicCronMarkOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CamedRoute: CamedRoute,
  DiretorSlugRoute: DiretorSlugRoute,
  LiganteSlugRoute: LiganteSlugRoute,
  PresidenteSlugRoute: PresidenteSlugRoute,
  SlugIndexRoute: SlugIndexRoute,
  ApiPublicCronMarkOverdueRoute: ApiPublicCronMarkOverdueRoute,
  ApiPublicPaymentsMpOauthCallbackRoute: ApiPublicPaymentsMpOauthCallbackRoute,
  ApiPublicPaymentsMpWebhookRoute: ApiPublicPaymentsMpWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
